version: "3.8"
services:
  gotify:
    image: "gotify/server:2.6.3"
    container_name: "gotify"
    environment:
      - "TZ=${TZ}"
      - "GOTIFY_REGISTRATION=${GOTIFY_REGISTRATION}"
    volumes:
      - "${APPDATA_PATH}/gotify/config:/app/data"
    ports:
      - "${PORT}:80"
    restart: "unless-stopped"
