version: "3.8"
services:
  homeassistant:
    image: "homeassistant/home-assistant:2025.5.3"
    container_name: "homeassistant"
    network_mode: "host"
    volumes:
      - "${APPDATA_PATH}/homeassistant/config:/config"
      - "/etc/localtime:/etc/localtime:ro"
      - "/run/dbus:/run/dbus:ro"
    restart: "unless-stopped"
