version: "3.8"
services:
  caddy-reverse-proxy:
    image: "caddy:2.10.0"
    container_name: "caddy-reverse-proxy"
    cap_add:
      - NET_ADMIN
    volumes:
      - "${APPDATA_PATH}/caddy-reverse-proxy/caddy:/etc/caddy"
      - "${APPDATA_PATH}/caddy-reverse-proxy/config:/config"
      - "${APPDATA_PATH}/caddy-reverse-proxy/data:/data"
      - "${APPDATA_PATH}/caddy-reverse-proxy/log:/var/log/caddy"
      - "${APPDATA_PATH}/caddy-reverse-proxy/srv:/srv"
    ports:
      - "${HTTP}:80"
      - "${HTTPS}:443"
    restart: "unless-stopped"
