version: "3.8"
services:
  adguardhome:
    image: "adguard/adguardhome:v0.107.62"
    container_name: "adguardhome"
    volumes:
      - "${APPDATA_PATH}/adguardhome/work:/opt/adguardhome/work"
      - "${APPDATA_PATH}/adguardhome/conf:/opt/adguardhome/conf"
    ports:
      - "${DNS_PORT}:53/tcp"
      - "${DNS_PORT}:53/udp"
      - "${TLS_PORT}:853/tcp"
      - "${ADMIN_PORT}:3000/tcp"
    restart: "unless-stopped"
