services:
  kopia:
    image: "kopia/kopia:0.20.1"
    container_name: "${CONTAINER_NAME}"
    hostname: "${HOSTNAME}"
    # Setup the server that provides the web gui
    command:
      - server
      - start
      - --disable-csrf-token-checks
      - --insecure
      - --address=0.0.0.0:51515
      - --server-username=${SERVER_USERNAME}
      - --server-password=${SERVER_PASSWORD}
    environment:
    # Set repository password
       - "KOPIA_PASSWORD=${KOPIA_PASSWORD}"
       - "USER=${USER}"
       - "TZ=${TZ}"
    volumes:
      # Mount local folders needed by kopia
      - "./config:/app/config"
      - "./cache:/app/cache"
      - "./logs:/app/logs"
      # Scripts path
      - "./scripts:/scripts"
      # Mount path for browsing mounted snaphots
      - "./tmp:/tmp:shared"
      # Mount repository location
      - "${BACKUP_PATH}:/repository"
      # Restore path
      - "${RESTORE_PATH}:/restore"
      # Mount local folders to snapshot
      - "${SOURCE_PATH}:/data:ro"
    ports:
      - "${PORT}:51515"
    restart: "unless-stopped"
