version: "3.8"
services:
  uptime-kuma:
    image: "louislam/uptime-kuma:1.23.16"
    container_name: "uptime-kuma"
    volumes:
      - "${APPDATA_PATH}/uptime-kuma/config:/app/data"
    ports:
      - "${PORT}:3001"
    restart: "unless-stopped"
